all: lab6a lab6b lab6c lab6d

lab6a: lab6a.c
	gcc -Wall -Wextra lab6a.c -o lab6a


lab6b: lab6b.c
	gcc -Wall -Wextra lab6b.c -o lab6b

lab6c: lab6c.cpp
	g++ -Wall -Wextra lab6c.cpp -o lab6c

lab6d: lab6d.cpp
	g++ -Wall -Wextra lab6d.cpp -o lab6d

clean:
	rm -rf lab6?.o lab6?
